services:
  db:
    image: postgres:16
    platform: linux/arm64/v8
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: >
      bash -c "
        rm -f /app/tmp/pids/server.pid &&
        bundle install &&
        bundle exec rails server -p 3000 -b '0.0.0.0'
      "
    volumes:
      - .:/app
      - bundle_data:/app/vendor/bundle
    environment:
      - NODE_ENV=development
      - CSS_ENV=development
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
  bundle_data:
  node_modules: